### ISSUE TITLE
The Laser Beam API is disabled. An error has occured during initialization.

### ISSUE THREAD

**Issue by Arini11** [SkytAsul/GuardianBeam#14]
The Laser Beam API is disabled. An error has occured during initialization.

I get this error. Any idea how I can solve it?

I'm using 1.16.5

[20:54:38 WARN]: java.lang.IllegalStateException: The Laser Beam API is disabled. An error has occured during initialization.
[20:54:38 WARN]: 	at me.arnaumas.altres.Laser.<init>(Laser.java:61)
[20:54:38 WARN]: 	at me.arnaumas.altres.Laser$GuardianLaser.<init>(Laser.java:309)
[20:54:38 WARN]: 	at me.arnaumas.commands.RaycastCommand.torre(RaycastCommand.java:85)
[20:54:38 WARN]: 	at me.arnaumas.events.EventsFacade.onMoures(EventsFacade.java:222)
[20:54:38 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source)
[20:54:38 WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:54:38 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:54:38 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:54:38 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1424)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[20:54:38 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[20:54:38 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by SkytAsul** [comment]
There is not enough informations. I need the error that occurred during first initialization.
Also, please try with latest version 2.2.3.

**Comment by SkytAsul** [comment]
Got no response.

**Comment by MiguVT** [comment]
@SkytAsul Same error here! im using slime world manager and its simple, trying to use it got The Laser Beam API is disabled. An error has occured during initialization.
