### ISSUE TITLE
GuardianBeam error when using Advanced Slime World Manager

### ISSUE THREAD

**Issue by MiguVT** [SkytAsul/GuardianBeam#25]
[17:13:11] [Server thread/INFO]: [GuardianBeam] [GuardianBeam] Found server version 1.20.4
[17:13:11] [Server thread/INFO]: [GuardianBeam] [GuardianBeam] Loaded mappings V1_20
[17:13:11] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.entity.boss.enderdragon.EntityEnderCrystal.<init>(net.minecraft.server.level.WorldServer,double,double,double)
[17:13:11] [Server thread/WARN]:     at java.base/java.lang.Class.getConstructor0(Class.java:3585)
[17:13:11] [Server thread/WARN]:     at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
[17:13:11] [Server thread/WARN]:     at MysteryBoxes-1.20.40-release.jar//com.xericker.mysteryboxes.compiled.Laser$Packets.<clinit>(Laser.java:795)
[17:13:11] [Server thread/WARN]:     at MysteryBoxes-1.20.40-release.jar//com.xericker.mysteryboxes.compiled.Laser.<init>(Laser.java:54)
[17:13:11] [Server thread/WARN]:     at MysteryBoxes-1.20.40-release.jar//com.xericker.mysteryboxes.compiled.Laser$GuardianLaser.<init>(Laser.java:311)
[17:13:11] [Server thread/WARN]:     at MysteryBoxes-1.20.40-release.jar//com.xericker.mysteryboxes.core.events.opening.themes.executors.UnderwaterTroubleTheme$1.run(UnderwaterTroubleTheme.java:102)
[17:13:11] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:13:11] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:13:11] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1650)
[17:13:11] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[17:13:11] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1529)
[17:13:11] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1230)
[17:13:11] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:13:11] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:840)
[17:13:11] [Server thread/ERROR]: [GuardianBeam] [GuardianBeam] Laser Beam reflection failed to initialize. The util is disabled. Please ensure your version (org.bukkit.craftbukkit.v1_20_R3) is supported.

**Comment by SkytAsul** [comment]
Does it work without the Advanced Slime World Manager?

**Comment by MiguVT** [comment]
Yes, working
![image](https://github.com/SkytAsul/GuardianBeam/assets/71216796/6b991e6f-8415-4cbf-8379-ff543309c413)

**Comment by SkytAsul** [comment]
Then ask the devs of SlimeWorldManager :sweat_smile: I don't know how they did their code. They are probably heavily editing server internals...

**Comment by MiguVT** [comment]
It's open source, can you check it pls?

**Comment by SkytAsul** [comment]
Unfortunately I don't have time for this, and the plugin is extremely large :(

**Comment by MiguVT** [comment]
It's ok i will search how to fix it, if i found a fix i will fix it and make pull request!
