### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Hosairis** [SkytAsul/GuardianBeam#3]
Idk know exactly how to reproduce it but when 2 players are getting shot at with 2 lasers at the same time with the laser view distance of 5 if you move back and forward and enter and exit the view distance ConcurrentModificationException happens

full stack trace:
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at ir.ciph3r.monstercrystal.utilities.Laser.moveInternal(Laser.java:230) ~[?:?]
	at ir.ciph3r.monstercrystal.utilities.Laser.moveStart(Laser.java:171) ~[?:?]
	at ir.ciph3r.monstercrystal.utilities.LaserRunnable.run(LaserRunnable.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

**Comment by SkytAsul** [comment]
Fixed in 2.0.0.
